= SUSE Linux Enterprise Real Time Documentation

image:https://travis-ci.org/SUSE/doc-slert.svg?branch=master["Build Status", link="https://travis-ci.org/SUSE/doc-slert"]

This is the source for the official SUSE Linux Enterprise Real Time documentation.

This repository hosts the documentation sources including translations (if
available) for the following products:

* SUSE Linux Enterprise Real Time Extension (SLERT)

Released versions of the documentation have been published at
https://www.suse.com/documentation/.


== Branches

**On Sep 12, 2019, we changed to a new branching model. We have
switched the default branch from `develop` to `master`.**

.Overview of important branches
[options="header"]
|================================================
| Name             | Purpose
| `master`         | doc development (latest development version)
| `maintenance/*`  | maintenance for released versions
| `trans`          | n/a
|================================================


== Contributing

If you would like to contribute, please fork this repository and send
pull requests.

* *Use the main branch* as the basis of your commits/of new feature branches.

. Make sure all validation checks are passed, and tag relevant SMEs from the development team (if applicable)
  and members of the SLE-RT doc team: Thomas Schraitle (@tomschr).

. Implement any required changes, or fix any merge conflicts if relevant. If you have any questions, ping a documentation team
  member in #team-suse-docs on Slack.

If you *created* a local clone or GitHub fork of this repo *before Sep 12, 2019, do the following*:

1. Make sure that your `master` and `develop` branches do not contain any important changes.
  If there are changes on either branch, export them using `git format-patch` or put them on a
  different branch.

1. Go to the master branch: `git checkout master`.


1. To pull the latest changes from the remote repository and to delete references to branches
   that do not exist anymore on the server, run the following command: `git pull --prune`.

1. Delete your local develop branch: `git branch -D develop`.

1. To check for stale local branches, run: `git branch -v`.
   For any branches marked as `[gone]`, check if you still need them. If not, delete them:
   `git branch -D BRANCHNAME`


== Writing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). Ideally, you should
  get these from the repository `Documentation:Tools`. However, slightly
  older versions are also available from the SLE and openSUSE repositories.
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF
** `$ daps -d DC-<YOUR_BOOK> html`: Build a HTML
** Learn more at https://opensuse.github.io/daps
